//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference2018.Datasources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSUPICEntities1 : DbContext
    {
        public PSUPICEntities1()
            : base("name=PSUPICEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<VIPMember> VIPMembers { get; set; }
        public virtual DbSet<VIPType> VIPTypes { get; set; }
    }
}
