//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference2018.Datasources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Submission()
        {
            this.Authors = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public string PCCode_Removed { get; set; }
        public string PaperCode { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Note { get; set; }
        public bool IsPublished { get; set; }
        public bool IsOral { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
