//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference2018.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conference2018.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Technology and Management.
        /// </summary>
        public static string Area1 {
            get {
                return ResourceManager.GetString("Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing Theory, Technologies and Applications.
        /// </summary>
        public static string Area2 {
            get {
                return ResourceManager.GetString("Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality and Tourism.
        /// </summary>
        public static string Area3 {
            get {
                return ResourceManager.GetString("Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Business.
        /// </summary>
        public static string Area4 {
            get {
                return ResourceManager.GetString("Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Language and Culture.
        /// </summary>
        public static string Area5 {
            get {
                return ResourceManager.GetString("Area5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call for Submission.
        /// </summary>
        public static string Schedule1LB {
            get {
                return ResourceManager.GetString("Schedule1LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December 1-31, 2017.
        /// </summary>
        public static string Schedule1Value {
            get {
                return ResourceManager.GetString("Schedule1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule1ValueOld {
            get {
                return ResourceManager.GetString("Schedule1ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Abstract Submission Deadline.
        /// </summary>
        public static string Schedule2LB {
            get {
                return ResourceManager.GetString("Schedule2LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 15, 2018.
        /// </summary>
        public static string Schedule2Value {
            get {
                return ResourceManager.GetString("Schedule2Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 2, 2018.
        /// </summary>
        public static string Schedule2ValueOld {
            get {
                return ResourceManager.GetString("Schedule2ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Notification.
        /// </summary>
        public static string Schedule3LB {
            get {
                return ResourceManager.GetString("Schedule3LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 1, 2018.
        /// </summary>
        public static string Schedule3Value {
            get {
                return ResourceManager.GetString("Schedule3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule3ValueOld {
            get {
                return ResourceManager.GetString("Schedule3ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera-Ready Submission Deadline.
        /// </summary>
        public static string Schedule4LB {
            get {
                return ResourceManager.GetString("Schedule4LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 15, 2018.
        /// </summary>
        public static string Schedule4Value {
            get {
                return ResourceManager.GetString("Schedule4Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule4ValueOld {
            get {
                return ResourceManager.GetString("Schedule4ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Bird Registration and Payment Deadline.
        /// </summary>
        public static string Schedule5LB {
            get {
                return ResourceManager.GetString("Schedule5LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 15, 2018.
        /// </summary>
        public static string Schedule5Value {
            get {
                return ResourceManager.GetString("Schedule5Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule5ValueOld {
            get {
                return ResourceManager.GetString("Schedule5ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Registration and Payment Deadline.
        /// </summary>
        public static string Schedule6LB {
            get {
                return ResourceManager.GetString("Schedule6LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March 10, 2018.
        /// </summary>
        public static string Schedule6Value {
            get {
                return ResourceManager.GetString("Schedule6Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 28, 2018.
        /// </summary>
        public static string Schedule6ValueOld {
            get {
                return ResourceManager.GetString("Schedule6ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Dates.
        /// </summary>
        public static string Schedule7LB {
            get {
                return ResourceManager.GetString("Schedule7LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March 11-12, 2018.
        /// </summary>
        public static string Schedule7Value {
            get {
                return ResourceManager.GetString("Schedule7Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule7ValueOld {
            get {
                return ResourceManager.GetString("Schedule7ValueOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule8LB {
            get {
                return ResourceManager.GetString("Schedule8LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule8Value {
            get {
                return ResourceManager.GetString("Schedule8Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Schedule8ValueOld {
            get {
                return ResourceManager.GetString("Schedule8ValueOld", resourceCulture);
            }
        }
    }
}
