//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference2018.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conference2018.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality and Tourism.
        /// </summary>
        public static string Area1 {
            get {
                return ResourceManager.GetString("Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Technology and Management.
        /// </summary>
        public static string Area2 {
            get {
                return ResourceManager.GetString("Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Business.
        /// </summary>
        public static string Area3 {
            get {
                return ResourceManager.GetString("Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology.
        /// </summary>
        public static string Area4 {
            get {
                return ResourceManager.GetString("Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Language and Culture Teaching.
        /// </summary>
        public static string Area5 {
            get {
                return ResourceManager.GetString("Area5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call for Submission.
        /// </summary>
        public static string lbSchedule1 {
            get {
                return ResourceManager.GetString("lbSchedule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Submission Deadline.
        /// </summary>
        public static string lbSchedule2 {
            get {
                return ResourceManager.GetString("lbSchedule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Notification.
        /// </summary>
        public static string lbSchedule3 {
            get {
                return ResourceManager.GetString("lbSchedule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera-Ready Submission Deadline.
        /// </summary>
        public static string lbSchedule4 {
            get {
                return ResourceManager.GetString("lbSchedule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Bird Registration and Payment Deadline.
        /// </summary>
        public static string lbSchedule5 {
            get {
                return ResourceManager.GetString("lbSchedule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Registration and Payment Deadline.
        /// </summary>
        public static string lbSchedule6 {
            get {
                return ResourceManager.GetString("lbSchedule6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Dates.
        /// </summary>
        public static string lbSchedule7 {
            get {
                return ResourceManager.GetString("lbSchedule7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbSchedule8 {
            get {
                return ResourceManager.GetString("lbSchedule8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December 1-31, 2017.
        /// </summary>
        public static string ScheduleValue1 {
            get {
                return ResourceManager.GetString("ScheduleValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 2, 2018.
        /// </summary>
        public static string ScheduleValue2 {
            get {
                return ResourceManager.GetString("ScheduleValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 1, 2018.
        /// </summary>
        public static string ScheduleValue3 {
            get {
                return ResourceManager.GetString("ScheduleValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 15, 2018.
        /// </summary>
        public static string ScheduleValue4 {
            get {
                return ResourceManager.GetString("ScheduleValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 15, 2018.
        /// </summary>
        public static string ScheduleValue5 {
            get {
                return ResourceManager.GetString("ScheduleValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 28, 2018.
        /// </summary>
        public static string ScheduleValue6 {
            get {
                return ResourceManager.GetString("ScheduleValue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March 11-12, 2018.
        /// </summary>
        public static string ScheduleValue7 {
            get {
                return ResourceManager.GetString("ScheduleValue7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScheduleValue8 {
            get {
                return ResourceManager.GetString("ScheduleValue8", resourceCulture);
            }
        }
    }
}
