//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSUPICLib.Datasources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegistID { get; set; }
        public int SubmissionID { get; set; }
        public int RegistTypeID { get; set; }
        public string ManyFields { get; set; }
        public Nullable<decimal> Fee { get; set; }
    
        public virtual RegistrationType RegistrationType { get; set; }
        public virtual Submission Submission { get; set; }
    }
}
