//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference2018 {
    
    
    public partial class organisation {
        
        /// <summary>
        /// rptGeneral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptGeneral;
        
        /// <summary>
        /// rptSteering control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptSteering;
        
        /// <summary>
        /// rptEnvPCChair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptEnvPCChair;
        
        /// <summary>
        /// rptEnvPC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptEnvPC;
        
        /// <summary>
        /// rptComPCChair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptComPCChair;
        
        /// <summary>
        /// rptComPC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptComPC;
        
        /// <summary>
        /// rptHTPCChair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptHTPCChair;
        
        /// <summary>
        /// rptHTPC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptHTPC;
        
        /// <summary>
        /// rptIBPCChair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptIBPCChair;
        
        /// <summary>
        /// rptIBPC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptIBPC;
        
        /// <summary>
        /// rptILPCChair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptILPCChair;
        
        /// <summary>
        /// rptILPC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptILPC;
        
        /// <summary>
        /// rptOrganising control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Conference2018.UserControls.ucPCChair rptOrganising;
    }
}
